name: timeline
version: '2.3.0'
summary: Timeline
description: |
  Timeline is a cross-platform application for displaying and navigating events on a timeline

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64

apps:
  timeline:
    command: var/opt/timeline/source/timeline.py
    extensions:
      - gnome-3-28
    plugs:
      - x11
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - home
      - removable-media
      - gsettings

parts:
  timeline:
    source: https://downloads.sourceforge.net/project/thetimelineproj/thetimelineproj/$SNAPCRAFT_PROJECT_VERSION/timeline-$SNAPCRAFT_PROJECT_VERSION.zip
    plugin: python
    python-version: python3
    python-packages:
      - humblewx
      - icalendar
      - Markdown
      - pysvg-py3
      - Pillow
    stage-packages:
      - python3-wxgtk4.0
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/var/opt/timeline
      cp -R timeline-$SNAPCRAFT_PROJECT_VERSION/* $SNAPCRAFT_PART_INSTALL/var/opt/timeline
